theme = 'ananke'
title = "Flying Snow Blog"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "zh-cn"
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "LZY"
  favicon = ""
  site_logo = ""
  description = "LZY的博客."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "Gitee"
url = "https://gitee.com/li_zengyi"
